const user = {

}
try {
    console.log(a)
} catch(err) {
    typeof(err)
    console.log(err.message)
    
}